/* Auto-generated by PUYA MCU PIN CONFIGURATOR */
#ifndef __INIT_H
#define __INIT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* Configuration Defines -----------------------------------------------------*/
//#define USE_GPIO
//#define USE_LCD
//#define USE_UART
//#define USE_ADC
//#define USE_TIMER
//#define USE_PWM
//#define USE_OUTPUT
//#define USE_INPUT

#define OUTPUT_TOGGLE(port, pin) HAL_GPIO_TogglePin(port, pin)

/* Peripheral handle externs */
extern TIM_HandleTypeDef htim1;

/* LCD setup */
#define LCD_RS_PIN           GPIO_PIN_3
#define LCD_RS_GPIO_PORT     GPIOB
#define LCD_EN_PIN           GPIO_PIN_4
#define LCD_EN_GPIO_PORT     GPIOB
#define LCD_D4_PIN           GPIO_PIN_5
#define LCD_D4_GPIO_PORT     GPIOB
#define LCD_D5_PIN           GPIO_PIN_6
#define LCD_D5_GPIO_PORT     GPIOB
#define LCD_D6_PIN           GPIO_PIN_0
#define LCD_D6_GPIO_PORT     GPIOB
#define LCD_D7_PIN           GPIO_PIN_1
#define LCD_D7_GPIO_PORT     GPIOB

#ifdef USE_LCD
/* LCD functions */
#include "lcd.h"
void APP_LCD_GpioConfig(void);
void LCD_Init(void);
#endif

/* Function prototypes */
void APP_ClockConfig(void);
void APP_GpioConfig(void);
void Error_Handler(void);
void APP_GpioConfig_Led(GPIO_TypeDef *port, uint16_t pin);
void APP_GpioConfig_Button(GPIO_TypeDef *port, uint16_t pin);
void LED_On(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin);
void LED_Off(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin);
uint8_t Button_Read(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin);

#ifdef __cplusplus
}
#endif

#endif /* __INIT_H */





